spring:
  application:
    name: notification-service
  cloud:
    config:
#      uri: http://localhost:8001 # http://config-service:8001
      fail-fast: true
      password: admin
      username: user
  config:
    import: configserver:http://config-service:8001