version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin

  postgres:
    image: postgres:14-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgresdb-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@examle.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    depends_on:
      - postgres

  ########## Services ##########
  config-service:
    container_name: config-service
    build: config-service
    ports:
      - "8001:8001"

  registry:
    container_name: registry
    build: registry
    ports:
      - "8761:8761"
    depends_on:
      - config-service

  gateway:
    container_name: gateway
    build: gateway
    ports:
      - "8989:8989"
    depends_on:
      - config-service
      - registry

  account-service:
    container_name: account-service
    build: account-service
    ports:
      - "8081:8081"
    depends_on:
      - config-service
      - registry
      - postgres

  bill-service:
    container_name: bill-service
    build: bill-service
    ports:
      - "8082:8082"
    depends_on:
      - config-service
      - registry
      - postgres

  deposit-service:
    container_name: deposit-service
    build: deposit-service
    ports:
      - "8083:8083"
    depends_on:
      - config-service
      - registry
      - postgres

  notification-service:
    container_name: notification-service
    build: notification-service
    ports:
      - "8084:8084"
    depends_on:
      - config-service
      - registry
      - postgres
      - rabbitmq

volumes:
  postgresdb-data:
