spring:
  application:
    name: registry
  cloud:
    config:
      # The configuration below is deprecated and doesn't work:
      # uri: http://localhost:8001 # http://config-service:8001
      fail-fast: true
      password: admin
      username: user
  config:
    import: configserver:http://config-service:8001

eureka:
  instance:
    preferIpAddress: true
  client:
    register-with-eureka: false
    fetch-registry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0
  server:
    peer-node-read-timeout-ms: 100000